alias ins='npm install'
alias run='npm run dev'

alias gst='git status'
alias ga='git add'
alias gcm='git commit -m'
alias gp='git push'
alias gpsu='git push --set-upstream'
alias gpd='git push --delete'
alias gba='git branch -a'
alias gbr='git branch --remote'
alias gbd='git branch -d'
alias gbm='git branch -m'
alias gb='git branch'
alias gc='git checkout'
alias gcb='git checkout -b'
alias gm='git merge'
alias gmnf='git merge --no-ff'
alias gfp='git fetch -p'

alias cls='clear'
alias project='cd c:/project/dmp-web-v2'
