alias ins='npm install'
alias run='npm run dev'

alias gst='git status'
alias ga='git add'
alias gcm='git commit -m'
alias gp='git push'
alias gpsu='git push --set-upstream'
alias gba='git branch -a'
alias gbr='git branch --remote'
alias gb='git branch'
alias gc='git checkout'
alias gcb='git checkout -b'

alias cls='clear'
alias project='cd c:/project/dmp-web-v2'
